### ISSUE TITLE
Cannot add new user

### ISSUE THREAD

**Issue by oe4dns** [pprugger/vmail-admin#1]
Adding a new user leads to an SQL Error:
 

> ERROR 1366 (22007) at line 1: Incorrect integer value: 'true' for column `vmail`.`accounts`.`enabled` at row 1

Reason seems to be that SQL expects '0' and '1' instead of 'true' and 'false' - changing that in the Definitions at the top fixes the problem.

```
new_user_enabled=true
new_user_sendonly=false
```

should be

```
new_user_enabled=1
new_user_sendonly=0
```

**Comment by pprugger** [comment]
Hey!
Fixed. Thanks for the Issue seems like i missed something in testing :)
